FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
    wget \
    ccache \
    build-essential \
    libssl-dev \
    libncurses5-dev \
    bison \
    cmake \
    valgrind \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*


RUN useradd -ms /bin/bash -G root developer

RUN mkdir /home/developer/ccache && \
	mkdir /home/developer/boost && \
    chown -R developer.developer /home/developer

ENV CCACHE_DIR /home/developer/ccache

WORKDIR /home/developer

CMD ["sleep", "10000000"]